### ISSUE TITLE
New upstream commits

### ISSUE THREAD

**Issue by Anon-Penguin** [buaazp/fasthttprouter#1]
There are multiple:

- Native OPTIONS header
- Better unicode upper/lowerase normalization
- Send "allow headers" on 405
- There are some new README changes; IDK if you want these to be updated downstream

How do you want to merge downstream? I was thinking about cherry-picking like this....

```bash
git remote add julienschmidt https://github.com/julienschmidt/httprouter
git fetch --all
git cherry-pick -n [commit_hash]
# Fix merge conflicts
git commit -m "Cherry pick [commit_hash]"
```

...but that would leave the source tree messy. Thoughts?

**Comment by buaazp** [comment]
Thanks for reminding me.
Now rebase done. Checkout the latest codes and have a try.

**Comment by Anon-Penguin** [comment]
Looks good. Thanks!
