### ISSUE TITLE
Please create release from latest code.

### ISSUE THREAD

**Issue by lunemec** [buaazp/fasthttprouter#10]
Glide still detects version 1.1 and the package was renamed from httprouter -> fasthttprouter and there is no release for it.

**Comment by yunspace** [comment]
I had also had similar issues with `fasthttp` library and various others. Managed to work around by using the commit hash as version so that glide won't get confused.

**Comment by buaazp** [comment]
Release done.

https://github.com/buaazp/fasthttprouter/releases
