### ISSUE TITLE
Static file example?

### ISSUE THREAD

**Issue by nkev** [buaazp/fasthttprouter#13]
Hi, I'm having no luck trying to implement a static file handler for a given request path. I can see your comment in Readme `...use a distinct sub-path for serving files, like /static/*filepath` but I cannot make it work. I tried this without success:

```GO
router.GET("/js/*filepath", fasthttp.FSHandler("../static/js", 0)) 
```

Could you please add a working example?

**Comment by headwindfly** [comment]
Maybe `ServeFiles` is which you looking for.
```
router.ServeFiles("/js/*filepath", "/path/to/jsdir")
```

**Comment by nkev** [comment]
Thank you! Works nicely. Please add that to your Readme to make it easier for the next person.

**Comment by buaazp** [comment]
OK, thanks for reminding me.

**Comment by QtRoS** [comment]
It is still unclear in 2018 how to make my static file handler work...

**Comment by wadrn** [comment]
please add readme :) I spent two hours to find out how to do this, so I think it is necessary
