### ISSUE TITLE
License-related question

### ISSUE THREAD

**Issue by kirillDanshin** [buaazp/fasthttprouter#26]
Hi.
I'm working on [gramework](https://github.com/gramework/gramework), and tonight I've integrated modified `fasthttprouter`. I was unable to solve integration problems without rewriting it to use `*gramework.Context` instead of `*fasthttp.RequestCtx`.
So, first of all, any fasthttprouter-related code placed in `fasthttprouter_*.go` files. Second, I modified [fasthttprouter file headers](https://github.com/gramework/gramework/blob/master/fasthttprouter_router.go#L1) so now it looks like this:
```
// Copyright 2013 Julien Schmidt. All rights reserved.
// Copyright (c) 2015-2016, 招牌疯子
// Copyright (c) 2017, Kirill Danshin
// Use of this source code is governed by a BSD-style license that can be found
// in the 3rd-Party License/fasthttprouter file.
```

This header placed in all `fasthttprouter_*.go` files except [`fasthttprouter_cache*.go`](https://github.com/gramework/gramework/blob/master/fasthttprouter_cache.go), that I've implemented from scratch.

Licenses placed in [this file](https://github.com/gramework/gramework/blob/master/3rd-Party%20Licenses/fasthttprouter) earlier, because I've forked fasthttprouter 5 days ago to implement hot paths caching.

So, I've changed all uses of fasthttp RequestCtx to gramework Context, slightly optimize router, implemented simple cache for hot paths, and changed all tests so they now passed as expected.

My question is simple: is it ok? Should I change/fix something?

/cc @julienschmidt

**Comment by buaazp** [comment]
In my opinion, that is OK. And welcome to open source your codes. But I don't know how @julienschmidt think about your modifying.

**Comment by julienschmidt** [comment]
Seems fine with me.

**Comment by kirillDanshin** [comment]
cool! thanks.
