### ISSUE TITLE
body size exceeds the given limit

### ISSUE THREAD

**Issue by kokizzu** [buaazp/fasthttprouter#27]
2017/03/27 16:12:59 error when serving connection "127.0.0.1:8083"<->"127.0.0.1:35588": body size exceeds the given limit

I got those error when uploading a big picture, how to set `maxRequestBodySize`?

**Comment by erikdubbelboer** [comment]
That's not something from `fasthttprouter`. It's in `fasthttp`: https://godoc.org/github.com/valyala/fasthttp#Server.MaxRequestBodySize

**Comment by buaazp** [comment]
👍 @erikdubbelboer

**Comment by erikdubbelboer** [comment]
I guess the issue can be closed.
