### ISSUE TITLE
Support more than one path param

### ISSUE THREAD

**Issue by jadbox** [buaazp/fasthttprouter#5]
The library does not support more than one path parameter being used (e.g. `/:path/:path2`) for a single route, otherwise it gives a gives a param error during startup.

**Comment by buaazp** [comment]
Maybe you set two conflicts path like these:
```
router.GET("/hello/:name", Hello)
router.GET("/:name/:word", MultiParams)
```
The path `/:name` is conflict with existed path `/hello`. Use more clear paths will fix the panic:

```
router.GET("/hello/:name", Hello)
router.GET("/multi/:name/:word", MultiParams)
```

Full codes is in [examples](https://github.com/buaazp/fasthttprouter/blob/master/examples/basic.go#L30)

**Comment by jadbox** [comment]
@buaazp I only have one route, and it seems to still fail. I'll try to put together a test case.

**Comment by buaazp** [comment]
You can paste a simple badcase here to reproduct.
