### ISSUE TITLE
Params vs Context

### ISSUE THREAD

**Issue by claygod** [buaazp/fasthttprouter#9]
Hello!
Tell me why you parameters of the URL is transmitted via **ps fasthttprouter.Params** instead of [func (*RequestCtx) UserValue](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.UserValue) in the context of.

**Comment by buaazp** [comment]
`fasthttprouter` is a fork of `httprouter`, and this `Params` struct come from here:
https://github.com/julienschmidt/httprouter/blob/master/router.go#L86

**Comment by yunspace** [comment]
@claygod there is a PR on this by the way https://github.com/buaazp/fasthttprouter/pull/8

**Comment by buaazp** [comment]
Now `UserValue` is available in master and releases.
